### ISSUE TITLE
python3.8 install weirdness

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/radiopadre#109]
It looks like the destination folder does not exist

```bash
    setup-radiopadre-virtualenv: copying /home/sphemakh/work/projects/meerkat-GPS/venv/lib/python3.6/site-packages/notebook/static/radiopadre-www to /tmp/pip-req-build-pwzvjxrj/radiopadre/html
    Traceback (most recent call last):
      File "./bin/setup-radiopadre-virtualenv", line 156, in <module>
        shutil.copy2(f"{PADRE_PATH}/icons/radiopadre-logo.ico", f"{notebook_static}/base/images/favicon-notebook.ico")
      File "/usr/lib/python3.8/shutil.py", line 432, in copy2
        copyfile(src, dst, follow_symlinks=follow_symlinks)
      File "/usr/lib/python3.8/shutil.py", line 261, in copyfile
        with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/sphemakh/work/projects/meerkat-GPS/venv/lib/python3.6/site-packages/notebook/static/base/images/favicon-notebook.ico'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-pwzvjxrj/setup.py", line 48, in <module>
        setup(
      File "/home/sphemakh/work/projects/meerkat-GPS/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-pwzvjxrj/setup.py", line 32, in run
        subprocess.check_call(command)
      File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['./bin/setup-radiopadre-virtualenv']' returned non-zero exit status 1.
    ----------------------------------------

```

**Comment by o-smirnov** [comment]
Jupyter must have changed some path structures. Could you please try ``find /home/sphemakh/work/projects/meerkat-GPS/venv/lib/python3.6/site-packages/notebook -name favicon-notebook.ico`` and tell me what it reports?

BTW, your venv path mentions python 3.6, and everything else is python 3.8. Can this be right?

**Comment by SpheMakh** [comment]
> BTW, your venv path mentions python 3.6, and everything else is python 3.8. Can this be right?

The python3 on this machine is 3.6, I should ask the admin to upgrade it.

**Comment by SpheMakh** [comment]
> The python3 on this machine is 3.6, I should ask the admin to upgrade it. 

Wait, this is on my laptop. I'm the admin!

But yes, this may be the issue. I could find the favicon-notebook.ico in the 3.8 path but in not the 3.6 one. As to how the python 3.6 branch exists, I have no idea

**Comment by o-smirnov** [comment]
Or maybe you did upgrade to 3.8, but now you're reinstalling radiopadre into a stale 3.6 environment?

Try running it with --venv-reinstall to blow everything away and rebuild. Be prepared to swear at pyregions when you do.

**Comment by SpheMakh** [comment]
I nuked the venv, and started another one. It looks like something in the install adds python3.6 (I do have both versions)

Before

```bash
(venv) sphemakh@makeba:~/work/projects/meerkat-GPS$ ls -lrt venv/lib
total 4
drwxrwxr-x 3 sphemakh sphemakh 4096 Mar 29 12:23 python3.8
```


After

```bash
(venv) sphemakh@makeba:~/work/projects/meerkat-GPS$ ls -lrt venv/lib
total 8
drwxrwxr-x 3 sphemakh sphemakh 4096 Mar 29 12:29 python3.8
drwxrwxr-x 3 sphemakh sphemakh 4096 Mar 29 12:32 python3.6

```

**Comment by o-smirnov** [comment]
So what exactly are your installation steps? You create a new 3.8 environment, and then?...

**Comment by SpheMakh** [comment]
```bash
python -m venv venv
(venv) sphemakh@makeba:~/work/projects/meerkat-GPS$ python --version
Python 3.8.5
pip install -U pip wheel
pip install radiopadre 
```

**Comment by o-smirnov** [comment]
Ah. Try ``pip install radiopadre-client``, that's the intended way of setting it up. The client will then take care of installing the main package wherever.

(That said, the main package shouldn't be breaking the venv like that, so I'll leave the bug open.)

**Comment by o-smirnov** [comment]
Ahh I see the problem. A quick and very dirty hack that should never have made it into production: https://github.com/ratt-ru/radiopadre/blob/master/bin/setup-radiopadre-virtualenv#L115

This is why we need code reviews!

**Comment by SpheMakh** [comment]
![shocked](https://media.giphy.com/media/3oEjHKvjqt5pssL99C/giphy.gif)

**Comment by o-smirnov** [comment]
I challenge anyone to look me in the eye and tell me they haven't done worse!

**Comment by o-smirnov** [comment]
1.1.2 is on PyPI -- can you check that it fixes this?
