### ISSUE TITLE
Radiopadre on Ilifu server

### ISSUE THREAD

**Issue by dionisionhadelo** [ratt-ru/radiopadre#118]
Hello,

I'm in need of help, I'm trying to run radiopadre on the ilufu server, but I get the following error:

(radio) (base) dio@dio-ThinkPad-T14-Gen-3:~$ run-radiopadre -V dio@slurm.ilifu.ac.za:/home/dio/radio
radiopadre.client [0.01s]: Welcome to the radiopadre client release 1.2.0!
radiopadre.client [0.01s]:   command line specifies BACKEND = venv
radiopadre.client: Opening ssh connection to dio@slurm.ilifu.ac.za. You may be prompted for your password.
radiopadre.client: Using remote client script within /users/dio/.radiopadre/venv
radiopadre.client: running radiopadre client on dio@slurm.ilifu.ac.za
radiopadre.client: dio@slurm.ilifu.ac.za: /users/dio/.radiopadre/venv/bin/run-radiopadre:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
radiopadre.client: dio@slurm.ilifu.ac.za:   __import__('pkg_resources').require('radiopadre-client==1.2.0')
radiopadre.client: dio@slurm.ilifu.ac.za: radiopadre.client [0.68s]: Welcome to the radiopadre client release 1.2.0!
radiopadre.client: dio@slurm.ilifu.ac.za: radiopadre.client [0.68s]: ERROR: /home/dio/radio is neither a directory nor a notebook
radiopadre.client: The ssh process to dio@slurm.ilifu.ac.za reports EOF
radiopadre.client: Remote session has exited with return code 1

**Comment by dionisionhadelo** [comment]
![Screenshot from 2024-05-09 13-41-37](https://github.com/ratt-ru/radiopadre/assets/73652124/27f4585e-5734-423e-a6ce-861f68eae63e)

**Comment by Athanaseus** [comment]
Hi @dionisionhadelo, thanks for reporting this issue.

A branch (`b1.2.3`) is under test and is meant to work with the current `slurm` setup on _ILIFU_.
Please have a look at this discussion here: https://github.com/ratt-ru/radiopadre-client/discussions/48#discussioncomment-8409231

Feel free to comment on the discussion. 

Best regards

**Comment by dionisionhadelo** [comment]
Thank you for the reply, I will have a look on it.

**Comment by dionisionhadelo** [comment]
All sorted now. Thank you.
