### ISSUE TITLE
install into existing venv, and request extra dependencies

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/radiopadre#21]
An option to add dependencies to the virtual environment that radiopadre creates would be nice. Something like 

```
run-remote-padre --venv-extras "pandas==1.2,crasa<=1.0.0"
```

**Comment by o-smirnov** [comment]
Instaling into existing venv is supported as of #56. ``--venv-extras`` is a good feature idea and should be easy to support now. Leaving the r1.0 milestone on it.
