### ISSUE TITLE
need to purge data/results-dirty.fits

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/radiopadre#22]
At some point I accidentally added `data/results-dirty.fits`, which is 24Mb and completely unnecessary (there is a much smaller `data/results.dirty.fits` which serves the example purposes just as well).

Can we completely expunge this file from the history and the repo? At the moment `git clone` takes a very long time because it's downloading that bastard as part of the repo.

**Comment by gijzelaerr** [comment]
I had a similar problem once, was not able to find the time to fix it. I think ludwig schwardt knows how to do this properly.
