### ISSUE TITLE
requirements.txt should list ipython-3, avoid 4

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/radiopadre#30]
Installing ipython through pip results in version 4, which doesn't work (at least on a bog-standard 14.04 LTS system). Can we explicitly put version 3 in the requirements?

**Comment by o-smirnov** [comment]
Hmmm, but the notebooks seem to be version 4 already... what a clusterfuck!

**Comment by gijzelaerr** [comment]
Latest ipython / jupyter should just work? Maybe uninstall the Debian
notebook package.
Op 13 mrt. 2016 12:56 schreef "Oleg Smirnov" <notifications@github.com>:

**Comment by o-smirnov** [comment]
Is it the recommended approach then to uninstall debian packages and pip install the lot? I thought that was frowned upon...

**Comment by gijzelaerr** [comment]
It is currently recommended to use a specific version from pip, unless it
is hard to install (takes long to compile, many dependencies).

pip is more flexible than debian packaging:
 * Not only for debian/Ubuntu
 * virtualenvs
 * You can any version available on pypi
 * Some packages are now also offered compiled in the form of wheels.
 * Much easier to make a package and get it distributed, no interaction
required.

Only disadvantage is compiled dependencies.

2016-03-14 11:31 GMT+02:00 Oleg Smirnov <notifications@github.com>:

> Is it the recommended approach then to uninstall debian packages and pip
> install the lot? I thought that was frowned upon...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/radio-astro/radiopadre/issues/30#issuecomment-196224103>
> .
>



-- 
Gijs Molenaar
http://pythonic.nl
