### ISSUE TITLE
if other projects are interested ...

### ISSUE THREAD

**Issue by ericmandel** [ratt-ru/radiopadre#33]
@o-smirnov Are you interested in talking to other projects about your work? JWST has contacted me re: future JS9/DS9 plans, including image display within Jupyter notebooks. If you are interested in talking to them, what would be your preferred method of contact? This issue?

**Comment by o-smirnov** [comment]
Should we keep this open, or has it died away for now?

**Comment by ericmandel** [comment]
@o-smirnov Yeah, you can close this, that little to-do last year was, so far as I can tell, an internal dispute at STScI that had nothing to do with us in the end ...

LSST is "also interested" in Jupyter-based analysis, but it's hard to figure out what they really want ... e.g., whether they have any interest in code not based on Python ...
