### ISSUE TITLE
integrate with virtualenv

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/radiopadre#34]
The current ``devel-lexy`` branch has my ugly kludge.

We need some kind of seamless process for when run-remote-padre is first run on a host with no radiopadre installed. Create virtualenv, install radiopadre, etc.

**Comment by gijzelaerr** [comment]
i recommend a makefile like this

https://github.com/gijzelaerr/spiel/blob/master/Makefile

**Comment by gijzelaerr** [comment]
```
all: .venv3/bin/jupyter-notebook
    .venv3/bin/jupyter-notebook

.venv3/:
    virtualenv -p python3 .venv3

.venv3/bin/jupyter-notebook: .venv3/
    .venv3/bin/pip install notebook
```
