### ISSUE TITLE
Help a noob to get this thing going #1: remote docker method

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/radiopadre#37]
I'm trying to remote connect to a machine that I have sudo privileges on. It's behind an ssh gateway, but I have ~/.ssh/config setup such that this is seamless for all other applications. I have installed Docker on the remote machine.

Here's my command on the local machine:

```
run-radiopadre heywoodl@aslxdaq04:/data/disk2/meerkat/thunderkat/GRS/radiopadre-default.ipynb
```

which results in:

```
run-radiopadre: Opening initial master connection to heywoodl@aslxdaq04. You may be prompted for your password.
heywoodl@aslxdaq04: /usr/bin/docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create?name=radiopadre-heywoodl-aedd2c865ae7498a900fd4ce313f6f84: dial unix /var/run/docker.sock: connect: permission denied.
```

I think the problem here is that although I have sudo privileges, /var is owned by root. 

Also: the readme documentation seems to be outdated, I don't have a `-d` switch, nor a `run-remote-padre` script.

**Comment by Mulan-94** [comment]
Hi @IanHeywood , maybe you can try adding yourself to the docker user group in that remote machine [as shown here](https://techoverflow.net/2017/03/01/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket/) and try again.
The `run-remote-padre` script is available at the `bin/` directory. Are you installing from pip?

**Comment by gijzelaerr** [comment]
did you add the remote self to the docker group? (don't forget to log out and log in again).

**Comment by gijzelaerr** [comment]
you can easily test if you can access the docker daemon with something simple like:
```
$ docker ps
```

**Comment by gijzelaerr** [comment]
ah sorry redundant answer, already answered by @Mulan-94 :) well done.

**Comment by IanHeywood** [comment]
I'm in, thanks!
