### ISSUE TITLE
depend on JS9 releases rather than git clone

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/radiopadre#66]
I don't know why, but the setup script can often hang on the JS9 git clone stage. 

It is probably a good idea (for stability's sake) to **not** track master anyway, but rather specify a JS9 release version and download the tarball. I see @ericmandel's got a 3.0 release nice and ready.

**Comment by ericmandel** [comment]
> t is probably a good idea (for stability's sake) to not track master anyway,
> 
Yeah, I was gonna mention this to you … it’s especially dangerous if I make a mistake and break master … it has happened for a few hours at a time ...

Eric

**Comment by o-smirnov** [comment]
Cool, thanks! Well it's using a fixed release now by default (3.0), with an option to git clone if somebody wants to live on the edge instead.
