### ISSUE TITLE
can't import name 'js9' (in rc6)

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/radiopadre#70]
https://github.com/ratt-ru/radiopadre-client/issues/11

**Comment by o-smirnov** [comment]
Things are a bit trickier than I thought.... @Athanaseus turns out data files listed in the ``MANIFEST.in`` file will only be copied over if they're under a package subdirectory... if they're in the top-level directory, they are quite cheerfully ignored. Anyway should be fixed by latest commit.

**Comment by adrianjhpc** [comment]
Maybe time to drop this whole python nonsense after all?

**Comment by o-smirnov** [comment]
Yeah let me quickly rewrite this whole thing in C++... just in time for 1.0-pre7?

**Comment by adrianjhpc** [comment]
Rust, surely...

**Comment by Athanaseus** [comment]
> Things are a bit trickier than I thought.... @Athanaseus turns out data files listed in the `MANIFEST.in` file will only be copied over if they're under a package subdirectory... if they're in the top-level directory, they are quite cheerfully ignored. Anyway should be fixed by latest commit.

Yeah this is strange unless I missed something. This isn't mentioned here https://wiki.python.org/moin/Distutils/Tutorial

**Comment by o-smirnov** [comment]
> Yeah this is strange unless I missed something.

You missed ``include_package_data=True`` in the call to ``setup()``. Looks like the manifest file controls what goes into the tarball in the first instance. What gets installed into site-packages is just a subset of that -- by default, this is just the *py files in the listed packages. The ``include_package_data`` option makes it install additional the files, but clearly, things one level up from the package directories are not considered "package data". 

(Well, I only learned this empirically, in the past hour...)

> Rust, surely...

Ach, it's not about languages... this is really a setuptools.py versus [C]Makefiles argument, surely? Which feels like swapping a particularly tedious flavour of crystal meth for a remarkably boring variety of crack...

**Comment by adrianjhpc** [comment]
😱 not CMake. I take it all back.

**Comment by Athanaseus** [comment]
Ah I see. Thanks for that.
