### ISSUE TITLE
Add an option to exclude line numbers from file

### ISSUE THREAD

**Issue by Athanaseus** [ratt-ru/radiopadre#74]
## Background
`radiopadre` offers an option to grep specific lines from a file either by index or matching string.
For instance, using indexes will result in the following output.

```
In [1]: from radiopadre import ls 
In [2]: test_info = ls("*test_info.txt")

In [3]: test_info[0][0:6]

Out [3] : 
0       Fields: 4
1	 ID   Code Name                RA               Decl           Epoch   SrcId      nRows
2	 0    T    0408-65             04:08:20.380000 -65.45.09.10000 J2000   0         722610
3	 1    T    J0538-4405          05:38:50.360000 -44.05.08.90000 J2000   1         511686
4	 2    T    PictorA             05:19:49.720000 -45.46.43.90000 J2000   2        7866684
5	 3    T    J0521+1638          05:21:09.890000 +16.38.22.10000 J2000   3         144522
```

## Proposal

Add an option to remove the file line numbers. Or if possible allow column grep too (space or comma separated), say I wanted to trim-off line numbers and `nRows` Column.
The expected result without line numbers should be:

```
Fields: 4
ID   Code Name                RA               Decl           Epoch   SrcId      nRows
0    T    0408-65             04:08:20.380000 -65.45.09.10000 J2000   0         722610
1    T    J0538-4405          05:38:50.360000 -44.05.08.90000 J2000   1         511686
2    T    PictorA             05:19:49.720000 -45.46.43.90000 J2000   2        7866684
3    T    J0521+1638          05:21:09.890000 +16.38.22.10000 J2000   3         144522
```

The expected result without line numbers and `nRow` should be:

```
Fields: 4
ID   Code Name                RA               Decl           Epoch   SrcId
0    T    0408-65             04:08:20.380000 -65.45.09.10000 J2000   0
1    T    J0538-4405          05:38:50.360000 -44.05.08.90000 J2000   1
2    T    PictorA             05:19:49.720000 -45.46.43.90000 J2000   2
3    T    J0521+1638          05:21:09.890000 +16.38.22.10000 J2000   3
```

NB: My first line only had 3 columns (including the line number).

PS: This can also be useful if a user needs to `tabulate` different elements in their own desired way while excluding less useful information.

**Comment by o-smirnov** [comment]
OK, so for line numbers, we could add property-setting functionality to the ``()`` operator. 

So, in your example, ``test_info[0][0:6](numbers=False)`` would return a "list-of-lines" object that would be identical to the original object, but would render itself without line numbers.

For your other suggestion, the ``extract()`` method already does something very close. It takes a regex and a list of group indices (or a slice), and returns a Table where each row is a matching line, and each column is a regex group.

So for the list of fields above, you could do something like

```python
test_info[0].extract("([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)\s+([^\s]+)", 
                               [0, 2, 3, 4])
```

...to match and extract the appropriate columns.

The regex support makes extract() very general, but perhaps a bit hard to use, so if we find ourselves doing this "split into columns and extract subset of columns" trick often, then perhaps I should implement a ``cut()`` method as a shortcut.

**Comment by Athanaseus** [comment]
Thanks a lot, let me try to manoeuvre with the regex and see if it has any limits.

**Comment by o-smirnov** [comment]
There are no limits. The only "limit" of regexes is that they will eventually fill your code with line noise, develop consciousness, and then fry your brains. Which is why I'm always looking out for simpler solutions....

**Comment by Athanaseus** [comment]
Surely I can deal with that for now :sneezing_face:
"simplicity is elegant"

**Comment by o-smirnov** [comment]
OK, implemented as discussed -- tack on ``(number=False)`` onto your object, and you get a new object that renders itself without line numbers.

**Comment by Athanaseus** [comment]
The numbers still show up.

```

obsinfo = ls("obsinfo/*-obsinfo.txt", section="Observation info")
obsinfo[-1][0:8].show(number=False)

```

![Screenshot from 2020-09-23 16-00-09](https://user-images.githubusercontent.com/16665629/94023001-fd5f2380-fdb5-11ea-83e9-9f58f899ad75.png)

**Comment by o-smirnov** [comment]
OK I see the problem. As implemented, ``obsinfo[-1][0:8](number=False).show()`` will do what you want.

However, it would be more consistent if ``show(number=False)`` also worked. The semantics of ``show()`` is to pass all optional arguments through to the renderer, so I think this can be fixed at https://github.com/ratt-ru/radiopadre/blob/master/radiopadre/textfile.py#L124 by adding a ``number`` keyword. I will do so accordingly.
